version: "3.7"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    links:
      - backend
    ports:
      - "80:80"
    volumes:
      - "./frontend/src:/app/src"
  backend:
    depends_on:
      - redis
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./backend/src:/app/src"
    links:
      - redis
networks:
  default:
    external:
      name: isarenabrawldeadyet.com
