version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "~/redis/data:/var/lib/redis"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./frontend/src:/app/src"
    depends_on:
      - redis
      - backend
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - "./backend/src:/app/src"
