on: push
name: Backend
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository files
        uses: actions/checkout@master
      - name: tests
        working-directory: ./backend
        run: |
          npm i
          npm run test
  deploy:
    # needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@master
      - name: Publish Docker Image to GPR
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: "isarenabrawldeadyet-backend"
          DOCKERFILE_PATH: "backend/Dockerfile"
          BUILD_CONTEXT: "backend/"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE }}
          script: |
            docker pull ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
            docker stop isarenabrawldeadyet.backend || true && docker rm isarenabrawldeadyet.backend || true
            docker run --detach -p 3000:3000 --name isarenabrawldeadyet.backend ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
