on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository files
        uses: actions/checkout@master
      - name: lint
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint
      # - name: e2e tests
      #   working-directory: ./frontend
      #   run: |
      #     npm ci
      #     npm run test:e2e
  containerize:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@master
      - name: Publish Docker Image to GPR
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: "isarenabrawldeadyet-frontend"
          DOCKERFILE_PATH: "frontend/Dockerfile"
          BUILD_CONTEXT: "frontend/"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
