on: push
name: Frontend
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository files
        uses: actions/checkout@master
      - name: lint
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Docker Image to GPR
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: "isarenabrawldeadyet-frontend"
          DOCKERFILE_PATH: "frontend/Dockerfile"
          BUILD_CONTEXT: "frontend/"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE }}
          script: |
            docker pull ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
            docker stop isarenabrawldeadyet_frontend || true && docker rm isarenabrawldeadyet_frontend || true
            docker run --detach -p 80:80 --name isarenabrawldeadyet_frontend --network isarenabrawldeadyet -d ${{ steps.docker.outputs.IMAGE_SHA_NAME }}